### ISSUE TITLE
sorry,but my project not can use

### ISSUE THREAD

**Issue by AiPacino** [xyproto/simplebolt#5]
# gitlab.com/aipacino/qrkeep/vendor/github.com/xyproto/simplebolt
vendor/github.com/xyproto/simplebolt/simplebolt.go:13:2: imported and not used: "gitlab.com/aipacino/qrkeep/vendor/github.com/etcd-io/bbolt" as bolt
vendor/github.com/xyproto/simplebolt/simplebolt.go:23:11: undefined: bbolt

**Comment by xyproto** [comment]
Update your vendored dependencies, and it should work.

I am unable to view your project on gitlab.com, otherwise I would have tested with:

```
go mod init
go get -u -v
go get -d -v
```

And seen if that would work.
